version: "3.1"
services:
  kavanest-mongo:
    container_name: kavanest-local-mongo
    image: mongo
    networks:
      - proxynet
    # volumes:
    # - ./data:/data/db
    ports:
      - "27017:27017"

networks:
  proxynet:
    name: kavanest-devnet
