name: kavanest-infra

namespace: kavanest

deployment:
  - name: kavanest-mongo
    image: mongo:bionic
    ports:
    - port: 27017
    volumes:
    - type: pvc
      name: mongo-store
      path: /data/db

pvc:
  - name: mongo-store
    storage: 100Mi

service:
  loadBalancer:
    - name: kavanest-mongo
      selector: kavanest-mongo
      port: 27017


